# Generated by Django 5.0 on 2026-03-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='cnn_accuracy',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='cnn_confidence',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='resnet_accuracy',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='resnet_confidence',
        ),
    ]
